{application,ndsclpto,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{ndsclpto_app,[]}},
              {env,[]},
              {modules,[ext_mod,ndsclpto,ndsclpto_app,ndsclpto_config,
                        ndsclpto_sup]}]}.
